"""empty message

<<<<<<<< HEAD:migrations/versions/5af6e221c4f6_.py
Revision ID: 5af6e221c4f6
Revises: 
Create Date: 2023-02-07 18:29:00.006480
========
Revision ID: 20f1eb7d8d78
Revises: 
Create Date: 2023-02-07 16:50:35.652187
>>>>>>>> d91588bcec184f8db86f3426e15bb82e8b285ed4:migrations/versions/20f1eb7d8d78_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/5af6e221c4f6_.py
revision = '5af6e221c4f6'
========
revision = '20f1eb7d8d78'
>>>>>>>> d91588bcec184f8db86f3426e15bb82e8b285ed4:migrations/versions/20f1eb7d8d78_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=2048), nullable=False),
    sa.Column('dataTime', sa.Date(), nullable=False),
    sa.Column('contact', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=1024), nullable=False),
    sa.Column('dataTime', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('projects')
    op.drop_table('user')
    # ### end Alembic commands ###
