"""empty message

Revision ID: 799b23eb8788
Revises: 7ecfdfb9594f
Create Date: 2023-02-08 15:09:54.792742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '799b23eb8788'
down_revision = '7ecfdfb9594f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('projects_category_key', type_='unique')
        batch_op.drop_constraint('projects_text_key', type_='unique')
        batch_op.drop_constraint('projects_title_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_unique_constraint('projects_title_key', ['title'])
        batch_op.create_unique_constraint('projects_text_key', ['text'])
        batch_op.create_unique_constraint('projects_category_key', ['category'])

    # ### end Alembic commands ###
