"""empty message

Revision ID: f820c4945cd7
Revises: db9de52b4bcd
Create Date: 2023-02-18 22:08:39.616558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f820c4945cd7'
down_revision = 'db9de52b4bcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('posts_text_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_unique_constraint('posts_text_key', ['text'])

    # ### end Alembic commands ###
